# Generated by Django 5.1.4 on 2025-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=245)),
                ('prix', models.CharField(default=0)),
                ('description', models.CharField(null=True)),
                ('indice_ecolo', models.FloatField()),
                ('image', models.URLField(null=True)),
                ('note', models.CharField(default=0)),
                ('site_marchand', models.URLField(null=True)),
                ('categorie', models.CharField(max_length=245)),
                ('nb_point', models.IntegerField(null=True)),
                ('lien_achat', models.URLField(null=True)),
            ],
        ),
    ]
