# Generated by Django 5.1.4 on 2025-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0002_commentaires_panier_produits_image_produits_nb_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='nom',
            field=models.CharField(default='O'),
        ),
    ]
