# Generated by Django 5.1.4 on 2025-03-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0003_utilisateurs_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilisateurs',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='username',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='Api_produits.utilisateurs'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='commentaires',
            field=models.ManyToManyField(related_name='produits', to='Api_produits.commentaires'),
        ),
        migrations.AlterField(
            model_name='élémentpanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='Api_produits.panier'),
        ),
    ]
