# Generated by Django 5.1.4 on 2025-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0004_alter_utilisateurs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='commentaires',
        ),
        migrations.AddField(
            model_name='produits',
            name='log_source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='source',
            field=models.CharField(null=True),
        ),
    ]
