# Generated by Django 5.1.4 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0005_remove_produits_commentaires_produits_log_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='log_source',
            new_name='lien_achat',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='nb_notes',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='source',
        ),
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.CharField(default='o', max_length=245),
            preserve_default=False,
        ),
    ]
