# Generated by Django 5.1.4 on 2025-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0006_rename_log_source_produits_lien_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='description',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
