# Generated by Django 5.1.4 on 2025-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0007_produits_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='notes',
        ),
        migrations.AddField(
            model_name='produits',
            name='note',
            field=models.CharField(default=0),
        ),
    ]
