# Generated by Django 5.1.4 on 2025-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_produits', '0008_remove_produits_notes_produits_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.CharField(default=0),
        ),
    ]
